# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Provide a Matrix and Return a Matrix
#' @description This function demonstrates how a Matrix is passed to C++ as
#' std::map<std::string, arma::colvec>. And how the C++ map is returned to R
#' as Matrix. Conversion is automatically handled by Rcpp as and wrap
#' functions defined in RcppExtModEx_types.cpp and RcppExtModEx_types.h.
#' @param mymap A Matrix with column names. The column names are used as keys
#' in the C++ map.
#' @export
mapIn_and_mapOut <- function(mymap) {
    .Call(`_RcppExtModEx_mapIn_and_mapOut`, mymap)
}

#' @title Create an Instance of the Foo Class
#' @description This function demonstrates how a Foo object is created and
#' returned to R.
#' @export
makeFoo <- function() {
    .Call(`_RcppExtModEx_makeFoo`)
}

#' @title Extract the testmap Field of a Foo Class Instance
#' @description This function takes an instance of the Foo class and returns
#' the testmap field. This is possible due to: 1) exposing Foo by setting
#' RCPP_EXPOSED_CLASS(Foo) in RcppExtModEx_types.h, and 2) using the
#' custom wrap handler defined in RcppExtModEx_types.cpp and RcppExtModEx_types.h.
#' @param instance An instance of the Foo class.
#' @export
getMap <- function(instance) {
    .Call(`_RcppExtModEx_getMap`, instance)
}

#' @title Set the testmap Field of a Foo Class Instance
#' @description This function takes an instance of the Foo class sets testmap
#' to the provided matrix field. This is possible due to: 1) exposing Foo by
#' setting RCPP_EXPOSED_CLASS(Foo) in RcppExtModEx_types.h, and 2) using
#' the custom as handler defined in RcppExtModEx_types.cpp and
#' RcppExtModEx_types.h.
#' @param instance An instance of the Foo class.
#' @param mymap A Matrix with column names. The column names are used as keys
#' in the C++ map.
#' @export
setMap <- function(instance, mymap) {
    invisible(.Call(`_RcppExtModEx_setMap`, instance, mymap))
}

