# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
mapIn_and_mapOut <- function(mymap) {
    .Call(`_RcppExtModEx_mapIn_and_mapOut`, mymap)
}

#' @export
makeFoo <- function() {
    .Call(`_RcppExtModEx_makeFoo`)
}

#' @export
getMap <- function(instance) {
    .Call(`_RcppExtModEx_getMap`, instance)
}

#' @export
setMap <- function(instance, mymap) {
    invisible(.Call(`_RcppExtModEx_setMap`, instance, mymap))
}

